### ISSUE TITLE
Gorilla CLI is not working and giving a "LoadingServer is unreachable" error

### ISSUE THREAD

**Issue by Balogunolalere** [gorilla-llm/gorilla-cli#66] opened 2024-09-02 11:07 UTC
I am encountering an issue where the Gorilla CLI is not working and is giving a "Server is unreachable" error. The specific error message is:

⠙ Loading
Server is unreachable.
Try updating Gorilla-CLI with 'pip install --upgrade gorilla-cli'

Steps to Reproduce:

    Open the terminal.
    Run any Gorilla CLI command (e.g., gorilla "generate 100 random characters into a file called test.txt").

Expected Behavior:
The command should execute successfully and display the expected output.

Actual Behavior:
The command fails with the error message:

⠙ Loading
Server is unreachable.
Try updating Gorilla-CLI with 'pip install --upgrade gorilla-cli'

Environment:

    Operating System: Ubuntu 22.04
    Gorilla CLI Version: gorilla-cli 0.0.10 
    Python Version: 3.10

Additional Information:

    I have tried updating the Gorilla CLI using pip install --upgrade gorilla-cli, but the issue persists.
    My internet connection and it is working fine.

**Comment by robert-fahey** [comment] 2024-09-09 09:14
I think the project is dead

**Comment by Balogunolalere** [comment] 2024-09-09 09:47
Hi @robert-fahey I did something similar and will love you to try it out, it is by no means perfect yet but you might love it. I am open to contributors 
 https://github.com/Balogunolalere/groq-cli
![IMG-20240906-WA0019](https://github.com/user-attachments/assets/d341ad85-f06e-4ca4-a288-0491abe916f4)
![IMG-20240906-WA0018](https://github.com/user-attachments/assets/e504bfc7-9ac0-4cc7-913f-2ccb1af879a5)
![IMG-20240906-WA0017](https://github.com/user-attachments/assets/d2f4f283-73ea-4c1e-8358-2b483e27aaf3)
![IMG-20240906-WA0016](https://github.com/user-attachments/assets/73341490-51fb-4745-9024-bd61a0fd68a7)

**Comment by larssb** [comment] 2024-09-11 18:51
@Balogunolalere what exactly are you showing us here?

**Comment by Balogunolalere** [comment] 2024-09-11 19:11
@larssb an alternative I created pending the resolution.

**Comment by shankscoder** [comment] 2024-09-20 11:37
Hold up! How is this closed if the solution is to use another tool? Sorry, this needs to be reopened as an issue that still persists with Gorilla.

@Balogunolalere Thank you for creating an alternative. Will check it out there, but lets keep the issues separate. Unclear on why you closed the issue, but that shouldn't have been done.

**Comment by lukeshingles** [comment] 2024-09-26 10:59
This is a duplicate of #64

**Comment by abitrolly** [comment] 2024-10-17 10:49
@Balogunolalere should be fixed now https://github.com/ShishirPatil/gorilla/issues/668#issuecomment-2418939366

**Closed as completed** 2024-10-17 11:06 UTC
